#!/bin/csh -fe

set SVN_OPTION = "--username svn-repo --password svn-repo --config-option servers:global:store-plaintext-passwords=yes"

echo "[setup]: start."

#
# setup svn repository sample.
#

# before setup
svn --version > /dev/null

cd repository/svn
svnadmin create svn-repo > /dev/null
make start > /dev/null

svn checkout $SVN_OPTION svn://localhost svn-repo-sample > /dev/null
cd svn-repo-sample
mkdir trunk
svn add trunk > /dev/null
svn commit $SVN_OPTION -m "svn の初回コミット。（trunk 作成）" > /dev/null
svn update $SVN_OPTION > /dev/null
cd ..
rm -fr svn-repo-sample

svn checkout $SVN_OPTION svn://localhost/trunk svn-repo-sample > /dev/null
cd svn-repo-sample
cp -pr ../../../data/svn/* .
svn add * > /dev/null
svn commit $SVN_OPTION -m "svn の二回目コミット。（trunk にテストファイルを追加。）" > /dev/null
svn update $SVN_OPTION > /dev/null
cd ..

cd ../..

#
# setup git repository sample.
#

# before setup
git --version > /dev/null

cd repository/git
git init --bare git-repo.git > /dev/null
git config --local user.name "Git-SVN Overwrite"
git config --local user.email "git-svn-overwrite@users"

git init git-repo-sample > /dev/null
cd git-repo-sample
git config --local user.name "Git-SVN Overwrite"
git config --local user.email "git-svn-overwrite@users"
git remote add origin ../git-repo.git > /dev/null
cp -pr ../../../data/git/* .
git add . > /dev/null
git commit -m "git の初回コミット。（master にテストファイルを追加。）" > /dev/null
(git push -u origin master > /dev/null) >& /dev/null
cd ..

cd ../..

echo "[setup]: end."
