#!/bin/csh -fe

echo "[teardown]: start."

cd repository/svn
make stop > /dev/null
rm -f svnserve.log
rm -fr svn-repo svn-repo-sample
cd ../..

cd repository/git
rm -fr git-repo.git git-repo-sample
cd ../..

if (-f .overwrite-prev_git_commit) then
  rm -f .overwrite-prev_git_commit
endif

echo "[teardown]: end."
