#!/bin/csh -f

echo "[test/git-svn-overwrite]: start."

set test_datetime = `date +"%Y%m%d%H%M%S"`
echo "[test/dry-run]: start."
./setup
echo "[execute]: start."
csh -fx ../git-svn-overwrite --dry-run repository/git/git-repo.git master svn://localhost trunk
echo "[execute]: end."
echo "[verify]: start."
cd repository/git/git-repo-sample
(git pull origin master > /dev/null) >& /dev/null
cd ../../svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
cd ../../..
diff -q -r --exclude=.git --exclude=.svn repository/git/git-repo-sample repository/svn/svn-repo-sample
if ($? == "0") then
  echo "Assertion Error."
  exit 2
endif
cd repository/svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
svn log -l 1
cd ../../..
echo "[verify]: end."
./teardown
echo "[test/dry-run]: end."

set test_datetime = `date +"%Y%m%d%H%M%S"`
echo "[test/commit]: start."
./setup
echo "[execute]: start."
../git-svn-overwrite repository/git/git-repo.git master svn://localhost trunk
echo "[execute]: end."
echo "[verify]: start."
cd repository/git/git-repo-sample
(git pull origin master > /dev/null) >& /dev/null
cd ../../svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
cd ../../..
diff -q -r --exclude=.git --exclude=.svn repository/git/git-repo-sample repository/svn/svn-repo-sample
if ($? != "0") then
  echo "Assertion Error."
  exit 2
endif
cd repository/svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
svn log -l 1
cd ../../..
echo "[verify]: end."
./teardown
echo "[test/commit]: end."

set test_datetime = `date +"%Y%m%d%H%M%S"`
echo "[test/commit_hash_file_commit]: start."
./setup
echo "[execute]: start."
../git-svn-overwrite --commit-hash-file ./.commit_hash_file repository/git/git-repo.git master svn://localhost trunk
echo "[execute]: end."
echo "[verify]: start."
cd repository/git/git-repo-sample
(git pull origin master > /dev/null) >& /dev/null
cd ../../svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
cd ../../..
diff -q -r --exclude=.git --exclude=.svn repository/git/git-repo-sample repository/svn/svn-repo-sample
if ($? != "0") then
  echo "Assertion Error."
  exit 2
endif
cd repository/svn/svn-repo-sample
svn update --username=svn-repo --password=svn-repo > /dev/null
svn log -l 1
cd ../../..
if (-f ./.commit_hash_file) then
  rm -f ./.commit_hash_file
else
  echo "Assertion Error."
  exit 3
endif
echo "[verify]: end."
./teardown
echo "[test/commit_hash_file_commit]: end."

echo "[test/git-svn-overwrite]: end."
