language: ruby
rvm:
  - 2.2
sudo: false
addons:
  apt:
    packages:
      - csh
      - git
      - subversion
      - subversion-tools
script:
  - csh --version
  - git --version
  - svn --version
  - cd test
  - ./test_git-svn-overwrite
