language: ruby
rvm:
  - 2.2
sudo: false
addons:
  apt:
    packages:
      - tcsh
      - git
      - subversion
before_script:
  - tcsh --version
  - git --version
  - svn --version
  - cd test
script:
  - ./test_git-svn-overwrite
